############################################################
#
# 用户微服务
# web访问端口号  约定：8103
#
############################################################
#生产环境
server:
  port: 8103

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

  # 设置域名，在java代码中获取，这里是资源配置
website:
  domain-name: portal-news.com